const movies=[
    {
        id:0,
        title:"spider man",
        image: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:1,
        title:"Wednesday",
        image: "https://lakewoodsnn.com/wp-content/uploads/2023/02/wednesday-720x900.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:2,
        title:"The flash",
        image: "https://m.media-amazon.com/images/M/MV5BYmQ0MDQ4ZTEtYWM2MS00ZDg3LWFhMTMtZGQ4MDQxMzAwNDcxXkEyXkFqcGdeQXVyMTU5OTA4NTIz._V1_.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:3,
        title:"Iron man",
        image: "https://m.media-amazon.com/images/M/MV5BMjE5MzcyNjk1M15BMl5BanBnXkFtZTcwMjQ4MjcxOQ@@._V1_.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:4,
        title:"Avengers Endgame",
        image: "https://m.media-amazon.com/images/I/81EvphYMiLL._AC_UF1000,1000_QL80_.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:5,
        title:"Super girl",
        image: "https://images.moviesanywhere.com/0418a5400ad9f3bcc5e639dca0f5df4e/95ca923e-a006-47df-acf3-f32a8ab98914.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:6,
        title:"Fast and Furious",
        image: "https://hips.hearstapps.com/hmg-prod/images/2-fast-2-furious-1623700657.jpeg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:7,
        title:"Kings man",
        image: "https://lumiere-a.akamaihd.net/v1/images/p_thekingsman_22436_98192ba9.jpeg?region=0%2C0%2C540%2C810",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:8,
        title:"Men in black",
        image: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8797139_p_v8_ad.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:9,
        title:"Scream",
        image: "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p18852_p_v10_al.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/04/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:10,
        title:"Mad max",
        image: "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "09/09/2023",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:11,
        title:"Hell boy",
        image: "https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/chameleon/title-movie/230667_HELLBOY_1400x2100_Eng.jpg?itok=SCu5bK3K",
        year: "2020",
        metascore_rating: "5",
        release_date: "03/09/2018",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:12,
        title:"Wakanda forever",
        image: "https://lumiere-a.akamaihd.net/v1/images/pp_disney_blackpanther_wakandaforever_1289_d3419b8f.jpeg?region=0%2C0%2C540%2C810",
        year: "2020",
        metascore_rating: "5",
        release_date: "08/04/2016",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:13,
        title:"Aqua man",
        image: "https://images.saymedia-content.com/.image/t_share/MTc0NDgzOTg0NTgxOTI4NTgy/aquaman-review-and-trailer-did-it-try-too-hard.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "05/02/2016",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
    {
        id:14,
        title:"Batman",
        image: "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_.jpg",
        year: "2020",
        metascore_rating: "5",
        release_date: "08/09/2012",
        runtime: "java",
        genre: "",
        directors: "",
        writers: "",
        actors: "",
        plots: "",
        awards: "",
        posters: "",
        production_company: "",
        website: "",
    },
]

export default movies